site_name: Frappe Technical Docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Introduction to the docs': 'index.md'
  - 'Introduction to Frappe':
      - 'What is Frappe?': 'intro-to-frappe/what-is-frappe.md'
      - 'Frappe Architecture': 'intro-to-frappe/frappe-architecture.md'
      - 'Frappe Bench': 'intro-to-frappe/frappe-bench.md'
  - 'Frappe Doctypes':
      - 'what is a Doctype?': 'doctypes/intro-to-doctypes.md'
      - 'Doctype Fields': 'doctypes/doctype-fields.md'
  - 'Frappe Sites':
      - 'What are frappe sites': 'sites/intro-to-sites.md'
  - 'Frappe Apps':
      - 'What are frappe apps': 'apps/intro-to-apps.md'

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
