site_name: Frappe Technical Docs
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - 'Introduction to the docs': 'index.md'
  - 'Introduction to Frappe':
      - 'What is Frappe?': intro-to-frappe/what-is-frappe.md
  - 'Frappe Doctypes':
      - 'what is a Doctype?': 'doctypes/intro-to-doctypes.md'
